import { VideoBackground } from '@/components/video-background/video-background'
import { Button } from '@/shared/lib/ui/button/button'
import localFont from 'next/font/local'
import Head from 'next/head'
import { useRouter } from 'next/router'

import styles from '@/styles/Home.module.css'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export default function Home() {
  const router = useRouter()

  return (
    <>
      <div style={{ display: 'flex', gap: '20px', left: '10px', position: 'fixed', top: '10px', zIndex: '3' }}>
        <Button onClick={() => router.push('registration')} variant={'secondary'}>
          Go to the Registration page
        </Button>
        <Button onClick={() => router.push('login')} variant={'secondary'}>
          Go to the Login page
        </Button>
      </div>
      <Head>
        <title>Todolists app</title>
        <meta content={'Generated by create next app'} name={'description'} />
        <meta content={'width=device-width, initial-scale=1'} name={'viewport'} />
        <link href={'/favicon.ico'} rel={'icon'} />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div style={{ fontSize: '34px', fontWeight: '500' }}>Todolists app with new API</div>
        </main>
        <footer className={styles.footer}></footer>
      </div>
      <VideoBackground />
    </>
  )
}
